spin_manifest_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "A webassembly component that adds oauth login functionality to your"
name = "oauth-login"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
auth_provider = { default = "github" } # or 'auth0'
success_url = { default = "/auth/success" }
error_url = { default = "/auth/error" }
scopes = { default = "openid,profile,email" }
client_id = { required = true, secret = true }
client_secret = { secret = true, default = "" } # required for 'github'; optional for 'auth0';
tenant = { default = "" } # required for 'auth0'

[[component]]
id = "login"
source = "login.wasm"
allowed_http_hosts = ["https://github.com"] # should include <tenant>.auth0.com for 'auth0'
key_value_stores = ["default"]

[component.trigger]
route = "/internal/login/..."

[component.build]
command = "tinygo build -target=wasi -tags=purego -gc=leaking -no-debug -o login.wasm main.go"
watch = ["**/*.go", "go.mod"]

[component.config]
auth_provider = "{{ auth_provider }}"
success_url = "{{ success_url }}"
error_url = "{{ error_url }}"
scopes = "{{ scopes }}"
client_id = "{{ client_id }}"
client_secret = "{{ client_secret }}"
tenant = "{{ tenant }}"
