spin_version = "1"
name = "{{project-name}}"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
auth_provider = { default = "github" }
scopes = { default = "openid,profile,email" }
client_id = { required = true, secret = true }
client_secret = { required = true, secret = true }

[[component]]
id = "oauth-login"
source = { url = "https://github.com/rajatjindal/oauth-login-spin/releases/download/v0.0.9/login.wasm", digest = "sha256:e370e06bb39981abb5ff62f82c8915fd0e7761ce936c0f0a6112fdd6d61910a6" }
allowed_http_hosts = ["https://github.com"]
key_value_stores = ["default"]
[component.trigger]
route = "/internal/login/..."
[component.config]
auth_provider = "{{ auth_provider }}"
scopes = "{{ scopes }}"
client_id = "{{ client_id }}"
client_secret = "{{ client_secret }}"